### ISSUE TITLE
The link to the archived site on the About page is not working.

### ISSUE THREAD

**Issue by hhopkins77** [sfg-taxonpages/coleorrhyncha#2]
This link     [http://coleorryncha.archive.speciesfile.org](https://coleorryncha.archive.speciesfile.org/)
under History on the About page is not working.

**Comment by jts1882** [comment]
It's a misspelling of coleorrhyncha and use of https instead of http.

On page https://coleorrhyncha.speciesfile.org/ the header and the links to Genus Hackeriella and Peloridiidae also have misspellings. 

Coleo**rryn**cha Species File
https://coleorryhncha.speciesfile.org/otus/915535/overview
https://coleorryhncha.speciesfile.org/otus/915518/overview
